steps:
  # Paso 1: Construir la imagen Docker del frontend
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker build \
        --build-arg VITE_API_URL=$_VITE_API_URL \
        -t gcr.io/$PROJECT_ID/nest-frontend ./frontend"

  # Paso 2: Subir la imagen a Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/nest-frontend"

  # Paso 3: Desplegar en Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - "gcloud run deploy nest-frontend \
      --image=gcr.io/$PROJECT_ID/nest-frontend \
      --platform=managed \
      --region=us-central1 \
      --allow-unauthenticated \
      --set-env-vars VITE_API_URL=$_VITE_API_URL"

options:
  logging: CLOUD_LOGGING_ONLY
